CREATE TABLE SUPPLIERS (
 SUPPLIER_ID NUMBER,
 CONSTRAINT SUPPLIERS_PK PRIMARY KEY (SUPPLIER_ID),
 COMPANY_NAME NVARCHAR2(50),
 CONTACT_NAME NVARCHAR2(50),
 CONTACT_TITLE NVARCHAR2(50),
 ADDRESS NVARCHAR2(50),
 CITY NVARCHAR2(50),
 REGION NVARCHAR2(50),
 POSTAL_CODE NUMBER,
 COUNTRY NVARCHAR2(50),
 PHONE NUMBER,
 FAX NUMBER,
 HOME_PAGE NVARCHAR2(200)
);

CREATE TABLE CATEGORIES (
 CATEGORY_ID,
 CONSTRAINT CATEGORIES_PK PRIMARY KEY (CATEGORY_ID),
 CATEGORY_NAME NVARCHAR2(50),
 DESCRIPTION NVARCHAR2(50),
 PICTURE NVARCHAR2(50) --?
);

CREATE TABLE EMPLOYEES (
 EMPLOYEE_ID NUMBER,
 CONSTRAINT EMPLOYEES_PK PRIMARY KEY (EMPLOYEE_ID),
 LAST_NAME NVARCHAR2(20),
 FIRST_NAME NVARCHAR2(20),
 TITLE NVARCHAR2(200),
 TITLE_OF_COUNTRESY NVARCHAR2(50),
 BIRTH_DATE TIMESTAMP,
 HIRE_DATE TIMESTAMP,
 ADDRESS NVARCHAR2(200),
 CITY NVARCHAR2(50),
 REGION NVARCHAR2(50),
 POSTAL_CODE NUMBER,
 COUNTRY NVARCHAR2(50),
 HOME_PHONE NUMBER,
 EXTENSION NVARCHAR2(50),
 PHOTO NVARCHAR2(50), --?
 NOTES NVARCHAR2(50),
 REPORTS_TO NVARCHAR2(50)
);


CREATE TABLE CUSTOMERS (
 CUSTOMER_ID NUMBER,
 CONSTRAINT CUSTOMERS_PK PRIMARY KEY (CUSTOMER_ID),
 COMPANY_NAME NVARCHAR2(50),
 CONTACT_TITLE NVARCHAR2(200),
 ADDRESS NVARCHAR2(200),
 CITY NVARCHAR2(50),
 REGION NVARCHAR2(50),
 POSTAL_CODE NUMBER,
 COUNTRY NVARCHAR2(50),
 PHONE NUMBER,
 FAX NUMBER
);

CREATE TABLE SHIPPERS (
 SHIPPER_ID NUMBER,
 CONSTRAINT SHIPPERS_PK PRIMARY KEY (SHIPPER_ID),
 COMPANY_NAME NVARCHAR2(50),
 PHONE NUMBER
);

CREATE TABLE ORDERS (
 ORDER_ID NUMBER,
 CONSTRAINT ORDERS_PK PRIMARY KEY (ORDER_ID),
 CUSTOMER_ID NUMBER,
 CONSTRAINT CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID),
 EMPLOYEE_ID NUMBER,
 CONSTRAINT EMPLOYEE_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMLOYEE_ID),
 ORDER_DATE TIMESTAMP,
 REQUIRED_DATE TIMESTAMP,
 SHIPPED_DATE TIMESTAMP,
 SHIP_VIA NVARCHAR2(50),
 FREIGHT NUMBER,
 SHIP_NAME NVARCHAR2(50),
 SHIP_ADDRESS NVARCHAR2(200),
 SHIP_CITY NVARCHAR2(50),
 SHIP_REGION NVARCHAR2(50),
 SHIP_POSTAL_CODE NUMBER,
 SHIP_COUNTRY NVARCHAR2(50)
);

CREATE TABLE PRODUCTS (
 PRODUCT_ID NUMBER,
 CONSTRAINT PRODUCTS_PK PRIMARY KEY (PRODUCT_ID),
 PRODUCT_NAME NVARCHAR2(50),
 SUPPLIER_ID NUMBER,
 CONSTRAINT SUPPLIER_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS (SUPPLIER_ID),
 CATEGORY_ID NUMBER,
 CONSTRAINT CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGRIES (CATEGORY_ID),
 QUANTITY_PER_UNIT NUMBER,
 UNIT_PRICE NUMBER,
 UNITS_IN_STOCK NUMBER,
 UNITS_ON_ORDER NUMBER,
 REORDERED_LEVEL NVARCHAR2(50),
 DISCONTINUED NUMBER
);

CREATE TABLE ORDER_DETAILS (
 ORDER_ID NUMBER,
 CONSTRAINT ORDER_DETAILS_PK PRIMARY KEY (ORDER_ID),
 CONSTRAINT ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
 PRODUCT_ID NUMBER,
 CONSTRAINT PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID),
 UNIT_PRICE NUMBER,
 QUANTITY NUMBER,
 DICOUNT NUMBER(*, 2)
);