ALTER TABLE PRODUCTS
DROP CONSTRAINT SUPPLIER_FK;

ALTER TABLE SUPPLIERS
DROP CONSTRAINT SUPLIERS_PK;

ALTER TABLE SUPLIERS
ADD CONSTRAINT PHONE_PK PRIMARY KEY (PHONE);

ALTER TABLE PRODUCTS
ADD CONSTRAINT SUPPLIERS_FK FOREIGN KEY (SUPPLIERS_ID) REFERENCES SUPPLIERS (PHONE);