CREATE TABLE PRODUCTS (
 PRODUCT_ID NUMBER,
 CONSTRAINT PRODUCTS_PK PRIMARY KEY (PRODUCT_ID),
 PRODUCT_NAME NVARCHAR2(50),
 SUPPLIER_ID NUMBER,
 CONSTRAINT SUPPLIER_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS (SUPPLIER_ID),
 CATEGORY_ID NUMBER,
 CONSTRAINT CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGRIES (CATEGORY_ID),
 QUANTITY_PER_UNIT NUMBER,
 UNIT_PRICE NUMBER,
 UNITS_IN_STOCK NUMBER,
 UNITS_ON_ORDER NUMBER,
 REORDERED_LEVEL NUMBER,
 DISCONTINUED NUMBER
);