CREATE TABLE FORUM_POSTS (
 ID NUMBER,
 CONSTRAINT FORUM_POSTS_PK PRIMARY KEY (ID),
 ID_SUBCATEGORY NUMBER,
 CONSTRAINT SUBCATEGORY_FK FOREIGN KEY (ID_SUBCATEGORY) REFERENCES FORUM_SUBCATEGORIES (ID),
 ID_USER NUMBER,
 CONSTRAINT USER_FK FOREIGN KEY (ID_USER) REFERENCES USERS (ID),
 PARENT_POST NUMBER,
 CONSTRAINT POST_FK FOREIGN KEY (PARENT_POST) REFERENCES FORUM_POSTS (ID),
 TTLE NVARCHAR2(90),
 CONTENT CLOB,
 IS_POLL BOOLEAN,
 DATE TIMESTAMP,
 IP NVARCHAR2(20)
);