CREATE TABLE FORUM_POLLS_OPTION_VOTES (
 ID NUMBER,
 CONSTRAINT FORUM_POLLS_OPTION_VOTES_PK PRIMARY KEY (ID),
 ID_POLL_OPTION NUMBER,
 CONSTRAINT POLL_OPTION_FK FOREIGN KEY (ID_POLL_OPTION) REFERENCES FORUM_POLLS_OPTIONS (ID),
 ID_USER NUMBER,
 CONSTRAINT USER_FK FOREIGN KEY (ID_USER) REFERENCES USERS (ID),
 DATE TIMESTAMP,
 IP NVARCHAR2(20)
);